/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      keyframes: {
        'slide-in': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-out': {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100%)', opacity: '0' },
        },
      },
      animation: {
        'slide-in': 'slide-in 0.4s ease-out',
        'slide-out': 'slide-out 0.4s ease-in',
      },
      boxShadow: {
        buttonShadow: '0px 3px 8px rgba(0, 0, 0, 0.24)',
        buttonShadowDark: '0px 3px 8px rgba(255, 255, 255, 0.1)',
        cardShadowLight: 'px 6px 12px -2px rgba(50, 50, 93, 0.25), 0px 3px 7px -3px rgba(0, 0, 0, 0.3)',
        cardShadowDark: '0px 3px 8px rgba(255, 255, 255, 0.1)',
      },
      borderRadius: {
        xs: '0.125rem',
      },
      fontFamily: {
        explora: ['Explora', 'serif'],
        libre: ['"Libre Caslon Text"', 'serif'],
      },
      colors: {        
        backgroundLight: '#E8D9CC',         
        paperLight: '#CCAA8F',              
        inputLight: '#FCF4ED',              
        primaryLight: '#0A7029',            
        primaryHoverLight: '#096125',       
        primaryActiveLight: '#074F1E',      
        primaryDisabledLight: '#A3BCA8',    
        primaryLightTone: '#C9E7D3',        
        primaryLightDarkTone: '#053F17',    
        secondaryLight:        '#D4A853',
        secondaryHoverLight:   '#BE9445',
        secondaryActiveLight:  '#A67D35',
        secondaryDisabledLight:'#E8CEAA',
        secondaryLightLightTone: '#F5E4C0',
        secondaryLightDarkTone:  '#A67D35',     
        errorLight: '#9B1B2E',              
        successLight: '#49AC03',            
        warningLight: '#C9631A',            
        infoLight: '#1A5F8A',             
        fontPrimaryLight: '#2D2D2D',        
        fontSecondaryLight: '#F0FDF4',      
        dividerLight: '#E8DDD5',           
        statusWantToReadLight: '#EDE0D0',
        statusWantToReadTextLight: '#6B4A2A',
        statusCurrentlyReadingLight: '#C8D9C0',
        statusCurrentlyReadingTextLight: '#2C4A26',
        statusReadLight: '#B8CCBC',
        statusReadTextLight: '#1A3520',
        statusDidNotFinishLight: '#DCCAC8',
        statusDidNotFinishTextLight: '#5C2422',
      
        backgroundDark: '#1E1A17',         
        paperDark: '#2C2420',               
        inputDark: '#F5EDE4',              
        primaryDark: '#E57F84',            
        primaryHoverDark: '#d66b70',        
        primaryActiveDark: '#b9555a',       
        primaryDisabledDark: '#f0c4c6',     
        primaryDarkLightTone: '#f9d9db',    
        primaryDarkDarkTone: '#E35159',     
        secondaryDark: '#F4EAE6',           
        secondaryHoverDark: '#e0d8d5',      
        secondaryActiveDark: '#cfc5c2',     
        secondaryDisabledDark: '#f6f1ef',   
        secondaryDarkLightTone: '#FAF8F7',  
        secondaryDarkDarkTone: '#FCE2D6',   
        fontPrimaryDark: '#1f1f1f',         
        fontSecondaryDark: '#E2EEF0',       
        dividerDark: '#3A302A',            
        errorDark: '#7A1A2A',               
        successDark: '#195D06',             
        warningDark: '#B85C18',             
        infoDark: '#1B4C6E',                
        statusWantToReadDark: '#3A2E1F',
        statusWantToReadTextDark: '#C4A882',
        statusCurrentlyReadingDark: '#253420',
        statusCurrentlyReadingTextDark: '#8AAF82',
        statusReadDark: '#1C2E20',
        statusReadTextDark: '#6A9870',
        statusDidNotFinishDark: '#342020',
        statusDidNotFinishTextDark: '#B08080',
      }
    }
  },
  plugins: [],
};
